using StealthOverhaul.Synth;
using System.Reflection;

namespace StealthOverhaul.Settings
{
    public class TopLevelSettings
    {
        #region Fields
        public string ActivePresetName = "[RAID] Lite";
        public Dictionary<string, StealthGameSettings> StealthGameSettingPresets = new()
        {
            {
                "[RAID] Lite",
                new()
                {
                    fSneakBaseValue = -4f,
                    fSneakDistanceAttenuationExponent = 5f,
                    fDetectionViewCone = 160f,
                    fDetectionSneakLightMod = -2f,
                    fSneakLightMult = 0.5f,
                    fSneakLightExteriorMult = 0.7f,
                    fSneakLightMoveMult = 0.2f,
                    fSneakLightRunMult = 0.7f,
                    iLightLevelInteriorMod = 25,
                    iLightLevelExteriorMod = 15,
                    iLightLevelMax = 200,
                    fSneakSoundsMult = 0.7f,
                    fSneakSoundLosMult = 0.28f,
                    fSneakEquippedWeightBase = 5f,
                    fSneakEquippedWeightMult = 0.25f,
                    fSneakActionMult = 1f,
                    fSneakRunningMult = 1.9f,
                    fSneakMaxDistance = 5000f,
                    fSneakExteriorDistanceMult = 1.3f,
                    fSneakFlyingDistanceMult = 3f,
                    fDetectProjectileDistanceNPC = 512f,
                    fDetectProjectileDistancePlayer = 1024f,
                    fDetectEventDistanceNPC = 512f,
                    fDetectEventDistancePlayer = 1536f,
                    iCrimeAlarmLowRecDistance = 1100,
                    iCrimeAlarmRecDistance = 2200,
                    fDeadReactionDistance = 700f,
                    fCombatStealthPointRegenAlertWaitTime = 15f,
                    fCombatStealthPointRegenDetectedEventWaitTime = 30f,
                    fCombatStealthPointRegenAttackedWaitTime = 50f,
                    fCombatStealthPointRegenLostWaitTime = 20f,
                    fCombatDetectionLostTimeLimit = 15f,
                    fCombatDetectionNoticedTimeLimit = 5f,
                    fActorAlertSoundTimer = 2f,
                    fDetectionEventExpireTime = 2f,
                    fSneakAlertMod = 1f,
                    fSneakCombatMod = -2f,
                    fSneakSleepBonus = -0.3f,
                    fSneakSkillMult = 0.08f,
                    fPlayerDetectionSneakMult = 0.7f,
                    fPlayerDetectionSneakBase = 5f,
                    fSneakPerceptionSkillMax = 100f,
                    fSneakPerceptionSkillMin = 0f,
                    fCombatStealthPointDrainMult = 3f,
                    fCombatStealthPointRegenMult = 0.08f,
                    fCombatStealthPointRegenMin = 2.5f,
                    iCombatStealthPointDetectionThreshold = 25,
                    iCombatStealthPointSneakDetectionThreshold = 70,
                    fCombatStealthPointAttackedMaxValue = 50f,
                    fCombatStealthPointDetectedEventMaxValue = 75f,
                    fCombatStealthPointMax = 100f,
                    fCombatSearchExteriorRadiusMax = 2560f,
                    fCombatSearchExteriorRadiusMin = 1536f,
                    fCombatSearchInteriorRadiusMax = 1536f,
                    fCombatSearchInteriorRadiusMin = 1024f,
                    fCombatSearchSightRadius = 1024f,
                    fCombatSearchInvestigateTime = 3.5f,
                    fCombatSearchLookTime = 1f,
                    fCombatSearchStartWaitTime = 1f,
                }
            },
            {
                "[RAID] Medium - Medium",
                new()
                {
                    fSneakBaseValue = -4f,
                    fSneakDistanceAttenuationExponent = 5f,
                    fDetectionViewCone = 160f,
                    fDetectionSneakLightMod = 6f,
                    fSneakLightMult = 0.6f,
                    fSneakLightExteriorMult = 1f,
                    fSneakLightMoveMult = 0.12f,
                    fSneakLightRunMult = 0.7f,
                    iLightLevelInteriorMod = 13,
                    iLightLevelExteriorMod = 10,
                    iLightLevelMax = 200,
                    fSneakSoundsMult = 0.7f,
                    fSneakSoundLosMult = 0.28f,
                    fSneakEquippedWeightBase = 5f,
                    fSneakEquippedWeightMult = 0.25f,
                    fSneakActionMult = 1f,
                    fSneakRunningMult = 2.15f,
                    fSneakMaxDistance = 5400f,
                    fSneakExteriorDistanceMult = 1.2f,
                    fSneakFlyingDistanceMult = 3f,
                    fDetectProjectileDistanceNPC = 512f,
                    fDetectProjectileDistancePlayer = 1024f,
                    fDetectEventDistanceNPC = 512f,
                    fDetectEventDistancePlayer = 1536f,
                    iCrimeAlarmLowRecDistance = 1500,
                    iCrimeAlarmRecDistance = 3000,
                    fDeadReactionDistance = 800f,
                    fCombatStealthPointRegenAlertWaitTime = 15f,
                    fCombatStealthPointRegenDetectedEventWaitTime = 25f,
                    fCombatStealthPointRegenAttackedWaitTime = 45f,
                    fCombatStealthPointRegenLostWaitTime = 20f,
                    fCombatDetectionLostTimeLimit = 15f,
                    fCombatDetectionNoticedTimeLimit = 30f,
                    fActorAlertSoundTimer = 2f,
                    fDetectionEventExpireTime = 2f,
                    fSneakAlertMod = 1f,
                    fSneakCombatMod = -1.5f,
                    fSneakSleepBonus = -0.3f,
                    fSneakSkillMult = 0.08f,
                    fPlayerDetectionSneakMult = 0.7f,
                    fPlayerDetectionSneakBase = 5f,
                    fSneakPerceptionSkillMax = 100f,
                    fSneakPerceptionSkillMin = 0f,
                    fCombatStealthPointDrainMult = 3f,
                    fCombatStealthPointRegenMult = 0.08f,
                    fCombatStealthPointRegenMin = 2.5f,
                    iCombatStealthPointDetectionThreshold = 35,
                    iCombatStealthPointSneakDetectionThreshold = 70,
                    fCombatStealthPointAttackedMaxValue = 50f,
                    fCombatStealthPointDetectedEventMaxValue = 75f,
                    fCombatStealthPointMax = 100f,
                    fCombatSearchExteriorRadiusMax = 2560f,
                    fCombatSearchExteriorRadiusMin = 1536f,
                    fCombatSearchInteriorRadiusMax = 1536f,
                    fCombatSearchInteriorRadiusMin = 1024f,
                    fCombatSearchSightRadius = 1024f,
                    fCombatSearchInvestigateTime = 3.5f,
                    fCombatSearchLookTime = 1f,
                    fCombatSearchStartWaitTime = 1f,
                }
            }
        };
        //public StealthGameSettings StealthRelatedGamesettings = new();
        #endregion Fields
    }
}
