using AIStealthOverhaul.Settings;
using Mutagen.Bethesda;
using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Synthesis;

namespace AIStealthOverhaul
{
    public static class Program
    {
        private static Lazy<TopLevelSettings> _lazySettings = null!;
        private static TopLevelSettings Settings => _lazySettings.Value;

        public static async Task<int> Main(string[] args)
            => await SynthesisPipeline.Instance
                   .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
                   .SetAutogeneratedSettings("Settings", "settings.json", out _lazySettings)
                   .SetTypicalOpen(GameRelease.SkyrimSE, "StealthOverhaul.esp")
                   .Run(args)
                   .ConfigureAwait(false);

        public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
        {
            Settings.ReadPresetFileIfSet();

            Console.WriteLine("\n--- PATCHER STARTING ---"); // begin

            Settings.AddToPatch(state, out int count);

            Console.WriteLine("--- PATCHER COMPLETE ---");
            Console.WriteLine($"Modified {count} GameSetting record{(count.Equals(1) ? "" : "s")}.\n");

            if (count.Equals(0)) Console.WriteLine("!!! No changes were made; something probably went wrong !!!");

            Settings.WritePresetFileIfSet();
        }
    }
}